#!/usr/bin/env ruby

require_relative "../lib/staples"

if ARGV[0].nil? || ARGV[0].empty?
  puts "Error: Application name required"
  puts "Usage: staples APP_NAME"
  exit 1
end

if ARGV.length > 1
  puts "Error: Too many arguments (#{ARGV.length} given)"
  puts "Usage: staples APP_NAME"
  exit 1
end

app_name = ARGV[0]

begin
  Staples::CLI.run(app_name)
  exit 0
rescue Staples::Error => e
  abort "Error: #{e.message}"
end
